## «*Olvidaba que en todo combate entre el fanatismo y el sentido común, pocas veces logra este último imponerse*».
### [Marguerite Yourcenar](https://es.wikipedia.org/wiki/Marguerite_Yourcenar)

# SI 02 NumPy

Actividad individual.

Resuelva los siguientes ejercicios con códigos que se ajusten al PEP8. Recuerde incluir los comentarios en el código y documentar las funciones con docstrings al estilo de Google.

**Importante:**

**no se permite la utilización de ciclos (for or while) para resolver los ejercicios.**

**todos los ejercicios deben ser resueltos con NumPy.**

## Ejercicio 00

Cree el arreglo_00 de 15 **columnas** y 1000 **filas** de la siguiente manera:

* cinco columnas con números aleatorios provenientes de una distribución normal de media 0 y desviación típica 1. Utilice como semilla el número de su documento de identidad sumado con el número de la columna.

* cinco columnas con números aleatorios enteros en los siguientes intervalos: 200 a 300, 400 a 600, 0 a 360, 100 a 900, y 1000 a 2000. Utilice como semilla el número de su documento de identidad.

* cinco columnas con números aleatorios binarios (0,1)

Muestre el resultado y las características del arreglo.

In [2]:
import numpy as np

def crear_arreglo():
    """Crea un arreglo con 15 columnas y 1000 filas según las especificaciones."""
    # Semilla para números aleatorios
    semilla = 

    # Cinco columnas con números aleatorios de distribución normal
    np.random.seed(semilla)
    normales = np.random.normal(0, 1, size=(1000, 5))

    # Cinco columnas con números aleatorios enteros en diferentes intervalos
    np.random.seed(semilla)
    enteros1 = np.random.randint(200, 301, size=(1000, 1))
    np.random.seed(semilla)
    enteros2 = np.random.randint(400, 601, size=(1000, 1))
    np.random.seed(semilla)
    enteros3 = np.random.randint(0, 361, size=(1000, 1))
    np.random.seed(semilla)
    enteros4 = np.random.randint(100, 901, size=(1000, 1))
    np.random.seed(semilla)
    enteros5 = np.random.randint(1000, 2001, size=(1000, 1))

    # Concatenar las columnas de enteros
    enteros = np.concatenate((enteros1, enteros2, enteros3, enteros4, enteros5), axis=1)

    # Cinco columnas con números aleatorios binarios
    np.random.seed(semilla)
    binarios = np.random.randint(0, 2, size=(1000, 5))

    # Concatenar todas las columnas
    arreglo_00 = np.concatenate((normales, enteros, binarios), axis=1)

    return arreglo_00

# Crear el arreglo según las especificaciones
arreglo_00 = crear_arreglo()

# Mostrar el arreglo y sus características
print("Arreglo generado:")
print(arreglo_00)
print("\nDimensiones del arreglo:", arreglo_00.shape)
print("Tipo de datos del arreglo:", arreglo_00.dtype)
print("Valor máximo en el arreglo:", np.max(arreglo_00))
print("Valor mínimo en el arreglo:", np.min(arreglo_00))
print("Promedio de todos los elementos del arreglo:", np.mean(arreglo_00))


Arreglo generado:
[[-0.27964673 -0.91044589 -1.90185029 ...  1.          1.
   0.        ]
 [-2.52684068 -0.83846735  0.82329859 ...  0.          0.
   1.        ]
 [ 0.61135173  0.66313594  0.50122045 ...  0.          0.
   0.        ]
 ...
 [-1.90964092 -0.28262182  0.03632868 ...  0.          1.
   0.        ]
 [ 0.05576052  0.58209306 -1.94336618 ...  0.          0.
   0.        ]
 [-0.96772893  0.4494499   0.16468222 ...  0.          1.
   0.        ]]

Dimensiones del arreglo: (1000, 15)
Tipo de datos del arreglo: float64
Valor máximo en el arreglo: 1999.0
Valor mínimo en el arreglo: -3.5781733426036997
Promedio de todos los elementos del arreglo: 194.10928194037675


## Ejercicio 01

Cree dos arreglos, de 15 columnas y 20 filas cada uno, a partir del arreglo_00.

Calcule el producto elemento a elemento entre los dos arreglos creados

Muestre el resultado y las características del arreglo que contiene el producto elemento a elemento.

In [4]:
import numpy as np

def crear_arreglo_01():
    """Crea dos arreglos de 15 columnas y 20 filas a partir del arreglo_00."""
    arreglo_00 = crear_arreglo()

    # Dividir el arreglo_00 en dos arreglos de 20 filas cada uno
    arreglo_01_a = arreglo_00[:20, :]
    arreglo_01_b = arreglo_00[20:40, :]

    return arreglo_01_a, arreglo_01_b

def calcular_producto_elemento_a_elemento(arreglo_a, arreglo_b):
    """Calcula el producto elemento a elemento entre dos arreglos."""
    producto = arreglo_a * arreglo_b
    return producto

# Crear dos arreglos de 15 columnas y 20 filas a partir de arreglo_00
arreglo_01_a, arreglo_01_b = crear_arreglo_01()

# Calcular el producto elemento a elemento entre los dos arreglos
producto_elemento_a_elemento = calcular_producto_elemento_a_elemento(arreglo_01_a, arreglo_01_b)

# Mostrar el resultado y sus características
print("Producto elemento a elemento:")
print(producto_elemento_a_elemento)
print("\nDimensiones del arreglo:", producto_elemento_a_elemento.shape)
print("Tipo de datos del arreglo:", producto_elemento_a_elemento.dtype)
print("Valor máximo en el arreglo:", np.max(producto_elemento_a_elemento))
print("Valor mínimo en el arreglo:", np.min(producto_elemento_a_elemento))
print("Promedio de todos los elementos del arreglo:", np.mean(producto_elemento_a_elemento))


Producto elemento a elemento:
[[-3.91449151e-02 -7.38395972e-01  2.00880880e+00  2.69933667e+00
  -3.73059717e-01  6.34330000e+04  2.44224000e+05  3.72960000e+04
   3.89267000e+05  1.62226100e+06  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.68082954e+00 -6.25428211e-01  2.01614487e-01  2.57482426e-01
   3.77191411e-01  6.91690000e+04  2.22222000e+05  5.53900000e+03
   7.51250000e+04  2.23491000e+06  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 9.30308078e-01 -9.34426708e-02  6.32659683e-02  6.50166289e-01
   1.45957637e+00  6.74880000e+04  2.73633000e+05  6.66710000e+04
   1.70236000e+05  2.59222700e+06  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 7.97666627e-01  3.45002946e-01  4.62782487e-01  6.19277173e-01
  -1.83466195e+00  5.78860000e+04  2.85784000e+05  1.77840000e+04
   3.98610000e+04  2.90872400e+06  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.0000

## Ejercicio 02

Cree dos arreglos, de 10 columnas y 10 filas cada uno, a partir del arreglo_00.

Calcule el producto matricial entre los dos arreglos creados

Muestre el resultado y las características del arreglo que contiene el producto matricial.

In [5]:
import numpy as np

def crear_arreglo_02():
    """Crea dos arreglos de 10 columnas y 10 filas a partir del arreglo_00."""
    arreglo_00 = crear_arreglo()
    # Dividir el arreglo_00 en dos arreglos de 10 filas cada uno
    arreglo_02_a = arreglo_00[:10, :]
    arreglo_02_b = arreglo_00[10:20, :]

    return arreglo_02_a, arreglo_02_b

def calcular_producto_matricial(arreglo_a, arreglo_b):
    """Calcula el producto matricial entre dos arreglos."""
    producto_matricial = np.dot(arreglo_a, arreglo_b.T)
    return producto_matricial

# Crear dos arreglos de 10 columnas y 10 filas a partir de arreglo_00
arreglo_02_a, arreglo_02_b = crear_arreglo_02()

# Calcular el producto matricial entre los dos arreglos
producto_matricial = calcular_producto_matricial(arreglo_02_a, arreglo_02_b)

# Mostrar el resultado y sus características
print("Producto matricial:")
print(producto_matricial)
print("\nDimensiones del arreglo:", producto_matricial.shape)
print("Tipo de datos del arreglo:", producto_matricial.dtype)
print("Valor máximo en el arreglo:", np.max(producto_matricial))
print("Valor mínimo en el arreglo:", np.min(producto_matricial))
print("Promedio de todos los elementos del arreglo:", np.mean(producto_matricial))


Producto matricial:
[[3109591.75088986 2371210.05232141 3168624.34383741 3122303.68681269
  3158750.57751377 2372079.35630464 3343965.77852682 2511039.74067674
  2696426.20634702 2672843.81175949]
 [4225599.8253995  3168968.99085605 4291277.07196284 4231438.78140285
  4276476.49585008 3169872.14819245 4594014.79160707 3425947.91333989
  3635283.1611172  3677239.57502714]
 [3646901.03266068 2810124.95286945 3806839.59279415 3780810.71120323
  3648121.11550751 2756253.15661841 4035803.3952124  3094216.45656895
  3061482.30548402 3072507.43180173]
 [3731179.21246069 2766626.39662984 3714172.29188776 3649285.33370926
  3814431.98079255 2823474.32805516 3984361.45365746 2933517.2965751
  3256274.04302673 3313142.07768084]
 [4199593.9985273  3069797.81046361 4130154.83806133 4044023.38010082
  4312124.6641158  3158483.41720553 4460109.80003847 3238077.85435779
  3699444.16862059 3785262.81663272]
 [2635110.71948818 1942438.53969368 2604354.03147238 2559744.79799065
  2699031.65814597 1998835

## Ejercicio 03

Cree un arreglo, de 15 columnas y 10 filas, a partir del arreglo_00.

Calcule y muestre la suma de cada una de las columnas y de cada una de las filas.

In [6]:
import numpy as np

def crear_arreglo_03():
    """Crea un arreglo de 15 columnas y 10 filas a partir del arreglo_00."""
    arreglo_00 = crear_arreglo()

    # Tomar las primeras 10 filas del arreglo_00
    arreglo_03 = arreglo_00[:10, :]

    return arreglo_03

def calcular_suma_columnas_y_filas(arreglo):
    """Calcula la suma de cada columna y de cada fila de un arreglo."""
    suma_columnas = np.sum(arreglo, axis=0)  # Suma de cada columna
    suma_filas = np.sum(arreglo, axis=1)  # Suma de cada fila

    return suma_columnas, suma_filas

# Crear un arreglo de 15 columnas y 10 filas a partir de arreglo_00
arreglo_03 = crear_arreglo_03()

# Calcular la suma de cada columna y de cada fila del arreglo
suma_columnas, suma_filas = calcular_suma_columnas_y_filas(arreglo_03)

# Mostrar el resultado
print("Suma de cada columna:")
print(suma_columnas)
print("\nSuma de cada fila:")
print(suma_filas)


Suma de cada columna:
[-7.58287573e+00 -2.25841168e+00  1.74787175e+00  7.96766430e-02
 -6.82835110e+00  2.55800000e+03  4.81000000e+03  2.05400000e+03
  5.30300000e+03  1.51010000e+04  9.00000000e+00  6.00000000e+00
  4.00000000e+00  2.00000000e+00  6.00000000e+00]

Suma de cada fila:
[2852.48825022 3458.57671475 3401.86125339 2923.78344037 3025.34347152
 1992.12661393 2608.69907442 3057.52530811 2945.02204769 3572.73173548]


## Ejercicio 04

Utilice el arreglo creado en el ejercicio anterior. Reconvierta el arreglo a uno de dimensión 5 columnas y 30 filas.

A partir de ese arreglo cree otro nuevo en el cual cada uno de los elementos de las filas es mayor que el promedio de la respectiva columna.

Muestre el arreglo obtenido y sus características.

In [7]:
import numpy as np

def reconstruir_arreglo(arreglo_entrada):
    """Reconstruye un arreglo de 5 columnas y 30 filas a partir de otro arreglo."""
    # Reconstruir el arreglo a 5 columnas y 30 filas
    arreglo_reconstruido = arreglo_entrada.reshape(30, 5)

    return arreglo_reconstruido

def crear_arreglo_filtrado(arreglo):
    """Crea un nuevo arreglo donde cada elemento de las filas es mayor que el promedio de su columna."""
    promedio_columnas = np.mean(arreglo, axis=0)  # Calcular el promedio de cada columna
    arreglo_filtrado = np.where(arreglo > promedio_columnas, arreglo, promedio_columnas)

    return arreglo_filtrado

# Reconstruir el arreglo de 5 columnas y 30 filas a partir del arreglo_03
arreglo_reconstruido = reconstruir_arreglo(arreglo_03)

# Crear un nuevo arreglo filtrado donde cada elemento de las filas es mayor que el promedio de su columna
arreglo_filtrado = crear_arreglo_filtrado(arreglo_reconstruido)

# Mostrar el arreglo filtrado y sus características
print("Arreglo filtrado:")
print(arreglo_filtrado)
print("\nDimensiones del arreglo:", arreglo_filtrado.shape)
print("Tipo de datos del arreglo:", arreglo_filtrado.dtype)
print("Valor máximo en el arreglo:", np.max(arreglo_filtrado))
print("Valor mínimo en el arreglo:", np.min(arreglo_filtrado))
print("Promedio de todos los elementos del arreglo:", np.mean(arreglo_filtrado))


Arreglo filtrado:
[[  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [ 277.          477.          333.          433.         1333.        ]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [ 263.          518.          191.          601.         1886.        ]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [ 296.          591.          209.          803.         1501.        ]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [ 281.          514.          114.          309.         1703.        ]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [  85.31390414  160.45805294   68.65826239  176.83598922  503.33905496]
 [ 274.          474.           7

## Ejercicio 05

Utilice el arreglo creado en el ejercicio 03.

Ordene cada columna de forma descendente, de mayor a menor, de forma independiente. Luego cree un nuevo arreglo con la concatenación de todas las columnas ordenadas.

Muestre el resultado y las características del arreglo.

In [8]:
import numpy as np

def ordenar_columnas_descendente(arreglo):
    """Ordena cada columna de un arreglo de forma descendente."""
    columnas_ordenadas = np.sort(arreglo, axis=0)[::-1]
    return columnas_ordenadas

def concatenar_columnas_ordenadas(arreglo):
    """Concatena todas las columnas ordenadas en un nuevo arreglo."""
    arreglo_concatenado = np.concatenate(arreglo, axis=0)
    return arreglo_concatenado

# Utilizar el arreglo creado en el ejercicio 03
arreglo_ordenado = ordenar_columnas_descendente(arreglo_03)

# Concatenar todas las columnas ordenadas en un nuevo arreglo
arreglo_concatenado = concatenar_columnas_ordenadas(arreglo_ordenado)

# Mostrar el resultado y sus características
print("Arreglo concatenado con columnas ordenadas:")
print(arreglo_concatenado)
print("\nDimensiones del arreglo:", arreglo_concatenado.shape)
print("Tipo de datos del arreglo:", arreglo_concatenado.dtype)
print("Valor máximo en el arreglo:", np.max(arreglo_concatenado))
print("Valor mínimo en el arreglo:", np.min(arreglo_concatenado))
print("Promedio de todos los elementos del arreglo:", np.mean(arreglo_concatenado))


Arreglo concatenado con columnas ordenadas:
[ 1.24763162e+00  1.39339405e+00  2.65161606e+00  1.08590089e+00
  8.18466007e-01  2.96000000e+02  5.91000000e+02  3.33000000e+02
  8.75000000e+02  1.99200000e+03  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.00000000e+00  6.11351731e-01
  6.63135940e-01  1.04840624e+00  1.04219415e+00 -2.27354821e-01
  2.81000000e+02  5.18000000e+02  3.22000000e+02  8.58000000e+02
  1.88600000e+03  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00 -2.79646732e-01  1.57278499e-01
  8.23298591e-01  8.87115341e-01 -2.52023273e-01  2.77000000e+02
  5.17000000e+02  3.00000000e+02  8.03000000e+02  1.77500000e+03
  1.00000000e+00  1.00000000e+00  1.00000000e+00  0.00000000e+00
  1.00000000e+00 -2.96174351e-01  4.48179161e-02  5.01220445e-01
  8.64433526e-01 -2.64674829e-01  2.74000000e+02  5.14000000e+02
  2.63000000e+02  6.14000000e+02  1.70300000e+03  1.00000000e+00
  1.00000000e+00  1.00000000e+00  0.00000000e+

## Ejercicio 06

Cree un arreglo, de 9 columnas y 9 filas, a partir del arreglo_00.

Agregue una nueva columna al final del arreglo que contenga la suma de cada una de las filas y otra columna que contenga el promedio de las nueve columnas originales del arreglo.

Muestre el resultado y las características del arreglo.

In [11]:
import numpy as np

def crear_arreglo_06():
    """Crea un arreglo de 9 columnas y 9 filas a partir del arreglo_00."""
    arreglo_00 = crear_arreglo()  # Utiliza la función creada en el ejercicio anterior

    # Tomar las primeras 9 filas del arreglo_00
    arreglo_06 = arreglo_00[:9, :]

    return arreglo_06

def agregar_columnas(arreglo):
    """Agrega dos nuevas columnas al arreglo: suma de filas y promedio de columnas."""
    # Calcular la suma de cada fila y agregar como nueva columna al final
    suma_filas = np.sum(arreglo, axis=1, keepdims=True)

    # Calcular el promedio de las nueve columnas originales y agregar como nueva columna al final
    promedio_columnas = np.mean(arreglo, axis=1, keepdims=True)

    # Concatenar las nuevas columnas al arreglo original
    arreglo_con_columnas_nuevas = np.concatenate((arreglo, suma_filas, promedio_columnas), axis=1)

    return arreglo_con_columnas_nuevas

# Crear un arreglo de 9 columnas y 9 filas a partir de arreglo_00
arreglo_06 = crear_arreglo_06()

# Agregar las nuevas columnas al arreglo
arreglo_con_columnas_nuevas = agregar_columnas(arreglo_06)

# Mostrar el resultado y sus características
print("Arreglo con columnas nuevas:")
print(arreglo_con_columnas_nuevas)
print("\nDimensiones del arreglo:", arreglo_con_columnas_nuevas.shape)
print("Tipo de datos del arreglo:", arreglo_con_columnas_nuevas.dtype)
print("Valor máximo en el arreglo:", np.max(arreglo_con_columnas_nuevas))
print("Valor mínimo en el arreglo:", np.min(arreglo_con_columnas_nuevas))
print("Promedio de todos los elementos del arreglo:", np.mean(arreglo_con_columnas_nuevas))


Arreglo con columnas nuevas:
[[-2.79646732e-01 -9.10445892e-01 -1.90185029e+00 -1.23827287e+00
   8.18466007e-01  2.77000000e+02  4.77000000e+02  3.33000000e+02
   4.33000000e+02  1.33300000e+03  1.00000000e+00  0.00000000e+00
   1.00000000e+00  1.00000000e+00  0.00000000e+00  2.85248825e+03
   1.90165883e+02]
 [-2.52684068e+00 -8.38467347e-01  8.23298591e-01  1.08590089e+00
  -9.67176700e-01  2.63000000e+02  5.18000000e+02  1.91000000e+02
   6.01000000e+02  1.88600000e+03  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.00000000e+00  3.45857671e+03
   2.30571781e+02]
 [ 6.11351731e-01  6.63135940e-01  5.01220445e-01  5.81129494e-01
  -1.49558423e+00  2.96000000e+02  5.91000000e+02  2.09000000e+02
   8.03000000e+02  1.50100000e+03  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  3.40186125e+03
   2.26790750e+02]
 [-1.25193030e+00 -9.91724831e-01  2.65161606e+00 -6.30240029e-01
  -9.94280531e-01  2.81000000e+02  5.14000000e+02  1.140

## Ejercicio 07

A partir de la columna del arreglo 00 que contiene los números enteros entre 0 y 360, genere un nuevo arreglo de 10 x 100.

Genere un nuevo arreglo en el que cada valor corresponda a la conversión de grados sexagesimales a radianes del arreglo que acaba de crear

Muestre el resultado y las características del arreglo.

In [13]:
import numpy as np

def crear_arreglo_07():
    """Crea un nuevo arreglo de 10x100 a partir de la columna del arreglo_00 con números entre 0 y 360."""
    arreglo_00 = crear_arreglo()

    # Extraer la columna del arreglo_00 con números entre 0 y 360
    columna_grados = arreglo_00[:, 10]

    # Repetir la columna de grados 10 veces (una vez por cada fila) y 10 veces más (100 en total)
    nuevo_arreglo = np.tile(columna_grados, (10, 10))

    return nuevo_arreglo

def convertir_a_radianes(arreglo):
    """Convierte los valores de un arreglo de grados sexagesimales a radianes."""
    arreglo_radianes = np.radians(arreglo)
    return arreglo_radianes

# Crear un nuevo arreglo de 10x100 a partir de la columna del arreglo_00 con números entre 0 y 360
nuevo_arreglo_07 = crear_arreglo_07()

# Convertir los valores del nuevo arreglo a radianes
arreglo_radianes = convertir_a_radianes(nuevo_arreglo_07)

# Mostrar el resultado y sus características
print("Arreglo de grados a radianes:")
print(arreglo_radianes)
print("\nDimensiones del arreglo:", arreglo_radianes.shape)
print("Tipo de datos del arreglo:", arreglo_radianes.dtype)
print("Valor máximo en el arreglo:", np.max(arreglo_radianes))
print("Valor mínimo en el arreglo:", np.min(arreglo_radianes))
print("Promedio de todos los elementos del arreglo:", np.mean(arreglo_radianes))


Arreglo de grados a radianes:
[[0.01745329 0.01745329 0.01745329 ... 0.         0.         0.01745329]
 [0.01745329 0.01745329 0.01745329 ... 0.         0.         0.01745329]
 [0.01745329 0.01745329 0.01745329 ... 0.         0.         0.01745329]
 ...
 [0.01745329 0.01745329 0.01745329 ... 0.         0.         0.01745329]
 [0.01745329 0.01745329 0.01745329 ... 0.         0.         0.01745329]
 [0.01745329 0.01745329 0.01745329 ... 0.         0.         0.01745329]]

Dimensiones del arreglo: (10, 10000)
Tipo de datos del arreglo: float64
Valor máximo en el arreglo: 0.017453292519943295
Valor mínimo en el arreglo: 0.0
Promedio de todos los elementos del arreglo: 0.008203047484373348


## Ejercicio 08

Cree un arreglo, de 15 columnas y 15 filas seleccionadas aleatoriamente (utilice el número de su documento de identidad como semilla), a partir del arreglo_00.

Calcule y muestre el determinante del arreglo, la transpuesta y la inversa.

In [20]:
import numpy as np

def crear_arreglo_aleatorio():
    """Crea un arreglo de 15 columnas y 15 filas seleccionadas aleatoriamente a partir del arreglo_00."""
    arreglo_00 = crear_arreglo()
    # Semilla para números aleatorios
    semilla = 

    # Configurar la semilla para números aleatorios
    np.random.seed(semilla)

    # Seleccionar aleatoriamente 15 filas del arreglo_00
    indices_filas = np.random.choice(arreglo_00.shape[0], 15, replace=False)
    arreglo_aleatorio = arreglo_00[indices_filas, :]

    return arreglo_aleatorio

# Crear un arreglo aleatorio de 15 columnas y 15 filas a partir del arreglo_00
arreglo_aleatorio = crear_arreglo_aleatorio()

# Calcular el determinante del arreglo
determinante = np.linalg.det(arreglo_aleatorio)

# Calcular la transpuesta del arreglo
transpuesta = arreglo_aleatorio.T

# Calcular la inversa del arreglo
inversa = np.linalg.inv(arreglo_aleatorio)

# Mostrar el resultado y sus características
print("Arreglo aleatorio:")
print(arreglo_aleatorio)
print("\nDeterminante del arreglo:", determinante)
print("\nTranspuesta del arreglo:")
print(transpuesta)
print("\nInversa del arreglo:")
print(inversa)


Arreglo aleatorio:
[[ 6.35533636e-01 -1.28837718e+00 -9.61232218e-01 -1.37751156e-01
   6.35786883e-01  2.19000000e+02  5.23000000e+02  2.18000000e+02
   2.05000000e+02  1.87600000e+03  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 4.14245144e-01  6.91554935e-01 -7.02911876e-01  1.90787974e+00
  -1.92489577e+00  2.15000000e+02  5.66000000e+02  6.00000000e+01
   1.86000000e+02  1.78200000e+03  0.00000000e+00  1.00000000e+00
   1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.13485425e-01  1.29633467e+00 -8.64377262e-01  4.31354490e-01
   9.04864816e-01  2.70000000e+02  4.26000000e+02  7.00000000e+01
   1.81000000e+02  1.13300000e+03  0.00000000e+00  0.00000000e+00
   1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 2.32422399e+00 -1.52543942e-01  1.07005594e+00 -1.83067019e+00
  -8.11300003e-01  2.40000000e+02  5.11000000e+02  3.44000000e+02
   4.01000000e+02  1.19100000e+03  0.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  1

## Ejercicio 09

Cree un arreglo, de 8 columnas y  8 filas, ambas seleccionadas aleatoriamente (utilice el número de su documento de identidad como semilla), a partir del arreglo_00.

Luego cree un arreglo de dimensión 1x8 con número reales aleatorios en el intervalo 0,10 (utilice el número de su documento de identidad como semilla).

Asuma que el primer arreglo representa los coeficientes de un sistema de ecuaciones lineales, y el segundo arreglo contiene las respectivas constantes. Encuentre la solución al sistema utilizando funciones de álgebra lineal de NumPy.

Muestre el valor de cada una de las variables que resuelve el sistema de ecuaciones.

In [19]:
import numpy as np

def crear_arreglo_coeficientes():
    """Crea un arreglo de 8 filas y 8 columnas seleccionadas aleatoriamente a partir del arreglo_00."""
    arreglo_00 = crear_arreglo()

    # Semilla para números aleatorios
    semilla = 
    # Configurar la semilla para números aleatorios
    np.random.seed(semilla)

    # Seleccionar aleatoriamente 8 filas del arreglo_00
    indices_filas = np.random.choice(arreglo_00.shape[0], 8, replace=False)
    arreglo_coeficientes = arreglo_00[indices_filas, :]

    # Seleccionar las primeras 8 columnas para hacer el arreglo cuadrado (8 filas y 8 columnas)
    arreglo_coeficientes = arreglo_coeficientes[:, :8]

    return arreglo_coeficientes

def crear_arreglo_constantes():
    """Crea un arreglo de 8 filas y 1 columna con números reales aleatorios en el intervalo [0, 10]."""
    # Semilla para números aleatorios
    semilla = 
    # Configurar la semilla para números aleatorios
    np.random.seed(semilla)

    # Generar un arreglo de 8 filas y 1 columna con números reales aleatorios en el intervalo [0, 10]
    arreglo_constantes = np.random.uniform(0, 10, (8, 1))

    return arreglo_constantes

# Crear el arreglo de coeficientes
arreglo_coeficientes = crear_arreglo_coeficientes()

# Crear el arreglo de constantes
arreglo_constantes = crear_arreglo_constantes()

# Resolver el sistema de ecuaciones lineales
solucion = np.linalg.solve(arreglo_coeficientes, arreglo_constantes)

# Mostrar la solución
print("Solución del sistema de ecuaciones:")
print(solucion)


Solución del sistema de ecuaciones:
[[ 18.26239155]
 [ 28.69803078]
 [-10.53537062]
 [-15.66652658]
 [  0.64782425]
 [  0.41632389]
 [ -0.25287233]
 [  0.07211261]]
